import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/sonner";
import AppWrapper from "@/components/app-wrapper";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.variable} antialiased bg-transparent`}>
          <AppWrapper>
            <Nav />
            {children}
          </AppWrapper>
          <Toaster position="bottom-right" />
        </body>
      </html>
    </ClerkProvider>
  );
}
