import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Nav from "@/components/nav";
import { Toaster } from "@/components/ui/sonner";
import Script from "next/script";
import AppWrapper from "@/components/app-wrapper";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${outfit.variable} antialiased`}>
          <AppWrapper>
            <Nav />
            {children}
          </AppWrapper>
          <Toaster position="bottom-right" />
        </body>
        <Script
          src="http://localhost:3000/embed.js"
          data-chatbot-slug="greenlife-a6b73f"
          data-position="bottom-right"
          data-width="350px"
          data-height="500px"
        />
      </html>
    </ClerkProvider>
  );
}
